### ISSUE TITLE
Cannot delete proof steps

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#212] opened 2018-05-30 09:57 UTC
During a derivation, clicking "Delete proof step" sometimes does nothing. This seems to happen when there are multiple branches.

**Comment by SaraWolffs** [comment] 2018-06-01 23:01
Unless there's a separate bug giving similar issues, the cause is https://github.com/scala/scala-swing/issues/73 , introduced between 2.0.1 and 2.0.2. Short version: Dialog.Result, the enum class, throws. Not "if you do this", just "if your code uses Dialog.Result in any way, that line throws". That was severe enough to cause them to declare 2.0.2 critically broken and push out 2.0.3 the day after the fix was merged.

Local build confirms bumping scala-swing to 2.0.3 in build.sbt fixes it. I'll fork and prepare a PR.

**Comment by SaraWolffs** [comment] 2018-06-01 23:48
Done and tested on a clean clone. If someone could merge #219 , that should fix it.

**Comment by jvdwetering** [comment] 2018-10-18 13:55
Closed by 8d24d41

**Closed as completed by jvdwetering** 2018-10-18 13:55 UTC
Labels: bug, ui, qpc2018
