### ISSUE TITLE
Rewriting with bang-boxes, boundary connections not respected

### ISSUE THREAD

**Issue by iislucas** [zxcalc/quantomatic#105] opened 2013-02-24 07:37 UTC
![Screen Shot 2013-02-23 at 23 33 13](https://f.cloud.github.com/assets/415450/189208/de12ad78-7e54-11e2-859a-85dc48940f77.png)
![Screen Shot 2013-02-23 at 23 33 22](https://f.cloud.github.com/assets/415450/189209/de29ee0c-7e54-11e2-8cb1-072787d7fa7b.png)
![Screen Shot 2013-02-23 at 23 33 27](https://f.cloud.github.com/assets/415450/189210/de427670-7e54-11e2-8163-6288acc8c168.png)
![Screen Shot 2013-02-23 at 23 34 12](https://f.cloud.github.com/assets/415450/189211/de491fca-7e54-11e2-9755-b98fe480d282.png)
![Screen Shot 2013-02-23 at 23 34 16](https://f.cloud.github.com/assets/415450/189212/de4ffe30-7e54-11e2-977d-c50e5e436b1d.png)
![Screen Shot 2013-02-23 at 23 34 31](https://f.cloud.github.com/assets/415450/189213/de4b4a70-7e54-11e2-8df7-1017d7b221c9.png)
![Screen Shot 2013-02-23 at 23 34 56](https://f.cloud.github.com/assets/415450/189214/de4e4306-7e54-11e2-88e6-5192764a4f27.png)

**Comment by akissinger** [comment] 2013-02-27 17:27
Looks fine to me (except that the label 'a' gets lost between screens 4 & 5, but I assume you changed that by hand?). The problem could be that you should put pi's inside the !-boxes in the pi-copy rule. The current (weird) rule is being applied correctly, with Ba expanded twice, Bb zero times, and Bc twice.

**Comment by randomguy3** [comment] 2013-03-07 18:23
I'm going to close this as "probably not a bug".

**Closed as completed by randomguy3** 2013-03-07 18:23 UTC
Labels: rewriting
